#!/usr/bin/env python3
from sys import argv
from googlesearch import search
query = ""
if len(argv) > 1:
    query = " ".join(argv[1:])
try:
    if len(argv) > 1:
        res = search(query)
        print('search results for :',query)
        for r in res:
            print(r)
    else :
        while search != 'exit' or search != 'quit':
            query = input("Googler>")
            res = search(query)
            print('search results for :',query)
            for r in res:
                print(r)
except Exception as e:
    print(e)